In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Toddler_Autism_dataset_July_2018.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1054 entries, 0 to 1053
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype 
---  ------                  --------------  ----- 
 0   Case_No                 1054 non-null   int64 
 1   A1                      1054 non-null   int64 
 2   A2                      1054 non-null   int64 
 3   A3                      1054 non-null   int64 
 4   A4                      1054 non-null   int64 
 5   A5                      1054 non-null   int64 
 6   A6                      1054 non-null   int64 
 7   A7                      1054 non-null   int64 
 8   A8                      1054 non-null   int64 
 9   A9                      1054 non-null   int64 
 10  A10                     1054 non-null   int64 
 11  Age_Mons                1054 non-null   int64 
 12  Qchat-10-Score          1054 non-null   int64 
 13  Sex                     1054 non-null   object
 14  Ethnicity               1054 non-null   object
 15  Jaun

In [4]:
df = df.rename(columns = {'Class/ASD Traits ' : 'ASD'})
df = df.rename(columns = {'A1' : 'Q1'})
df = df.rename(columns = {'A2' : 'Q2'})
df = df.rename(columns = {'A3' : 'Q3'})
df = df.rename(columns = {'A4' : 'Q4'})
df = df.rename(columns = {'A5' : 'Q5'})
df = df.rename(columns = {'A6' : 'Q6'})
df = df.rename(columns = {'A7' : 'Q7'})
df = df.rename(columns = {'A8' : 'Q8'})
df = df.rename(columns = {'A9' : 'Q9'})
df = df.rename(columns = {'A10' : 'Q10'})
df = df.rename(columns = {'Age_Mons' : 'Age in Months'})
df = df.rename(columns = {'Sex' : 'Gender'})
df = df.rename(columns = {'Qchat-10-Score' : 'Score out of 10'})
df = df.rename(columns = {'Ethnicity' : 'Region'})
df

Case_No  Q1  Q2  Q3  Q4  Q5  Q6  Q7  Q8  Q9  Q10  Age in Months  \
0           1   0   0   0   0   0   0   1   1   0    1             28   
1           2   1   1   0   0   0   1   1   0   0    0             36   
2           3   1   0   0   0   0   0   1   1   0    1             36   
3           4   1   1   1   1   1   1   1   1   1    1             24   
4           5   1   1   0   1   1   1   1   1   1    1             20   
...       ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...            ...   
1049     1050   0   0   0   0   0   0   0   0   0    1             24   
1050     1051   0   0   1   1   1   0   1   0   1    0             12   
1051     1052   1   0   1   1   1   1   1   1   1    1             18   
1052     1053   1   0   0   0   0   0   0   1   0    1             19   
1053     1054   1   1   0   0   1   1   0   1   1    0             24   

      Score out of 10 Gender          Region Jaundice Family_mem_with_ASD  \
0                   3      f  middle eastern      yes                  no   
1                   4      m  White European      yes                  no   
2                   4      m  middle eastern      yes                  no   
3                  10      m        Hispanic       no                  no   
4                   9      f  White European       no                 yes   
...               ...    ...             ...      ...                 ...   
1049                1      f  White European       no                 yes   
1050                5      m           black      yes                  no   
1051                9      m  middle eastern      yes                  no   
1052                3      m  White European       no                 yes   
1053                6      m           asian      yes                 yes   

     Who completed the test  ASD  
0             family member   No  
1             family member  Yes  
2             family member  Yes  
3             family member  Yes  
4             family member  Yes  
...                     ...  ...  
1049          family member   No  
1050          family member  Yes  
1051          family member  Yes  
1052          family member   No  
1053          family member  Yes  

[1054 rows x 19 columns]

In [44]:
x = df.drop('Case_No' , axis = 1)
x = x.drop('ASD', axis = 1)
y = df['ASD']

In [26]:
x.shape, y.shape

((1054, 18), (1054,))

In [27]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 36)

In [28]:
obj_cols = x_train.select_dtypes(include = 'object').columns
obj_cols

Index(['Gender', 'Region', 'Jaundice', 'Family_mem_with_ASD',
       'Who completed the test', 'ASD'],
      dtype='object')

In [29]:
float_cols = x_train.select_dtypes(include = 'int64').columns
float_cols

Index(['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10',
       'Age in Months', 'Score out of 10'],
      dtype='object')

In [30]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

le.fit(y_train)

LabelEncoder()

In [31]:
y_train_processed = le.transform(y_train)
y_test_processed = le.transform(y_test)

In [32]:
y_train_processed

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,

In [33]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = [x_train[i].unique() for i in obj_cols])
oe.fit(x_train[obj_cols])
x_train_cat_encoded = oe.transform(x_train[obj_cols])
x_test_cat_encoded = oe.transform(x_test[obj_cols])

In [34]:
x_train_cat_encoded

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0.]])

In [35]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(x_train[float_cols])

x_train_float_encoded = scaler.transform(x_train[float_cols])
x_test_float_encoded = scaler.transform(x_test[float_cols])

In [36]:
x_train_float_encoded

array([[0.        , 1.        , 0.        , ..., 1.        , 0.70833333,
        0.5       ],
       [1.        , 1.        , 1.        , ..., 0.        , 1.        ,
        0.8       ],
       [1.        , 1.        , 0.        , ..., 1.        , 0.125     ,
        0.7       ],
       ...,
       [1.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.4       ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.75      ,
        0.6       ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.5       ,
        0.5       ]])

In [37]:
x_train_processed = np.hstack((x_train_cat_encoded, x_train_float_encoded))
x_test_processed = np.hstack((x_test_cat_encoded, x_test_float_encoded))

In [38]:
feature_names = np.concatenate([obj_cols, float_cols])

In [39]:
x_train_final = pd.DataFrame(x_train_processed, columns = feature_names)

In [40]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train_processed, y_train_processed)
y_pred = lr.predict(x_test_processed)
print(accuracy_score(y_test_processed, y_pred))
print(confusion_matrix(y_test_processed, y_pred))

1.0
[[ 66   0]
 [  0 145]]


In [41]:
le.inverse_transform([0,1])

array(['No', 'Yes'], dtype=object)

In [42]:
df2 = pd.read_csv("autism_data.csv")

In [45]:
X = df2.drop('Case_No' , axis = 1)
X = X.drop('Score out of 10', axis = 1)
Y = df2['Score out of 10']
X.shape, Y.shape

((4, 16), (4,))

In [46]:
x.shape, y.shape

((1054, 17), (1054,))

In [47]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 36)

In [48]:
obj_cols = x_train.select_dtypes(include = 'object').columns
obj_cols

Index(['Gender', 'Region', 'Jaundice', 'Family_mem_with_ASD',
       'Who completed the test'],
      dtype='object')

In [49]:
float_cols = x_train.select_dtypes(include = 'int64').columns
float_cols

Index(['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10',
       'Age in Months', 'Score out of 10'],
      dtype='object')

In [50]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

le.fit(y_train)

LabelEncoder()

In [51]:
y_train_processed = le.transform(y_train)
y_test_processed = le.transform(y_test)

In [52]:
y_train_processed

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1,

In [53]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = [x_train[i].unique() for i in obj_cols])
oe.fit(x_train[obj_cols])
x_train_cat_encoded = oe.transform(x_train[obj_cols])
x_test_cat_encoded = oe.transform(x_test[obj_cols])

In [54]:
x_train_cat_encoded

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [55]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(x_train[float_cols])

x_train_float_encoded = scaler.transform(x_train[float_cols])
x_test_float_encoded = scaler.transform(x_test[float_cols])

In [56]:
x_train_float_encoded

array([[0.        , 1.        , 0.        , ..., 1.        , 0.70833333,
        0.5       ],
       [1.        , 1.        , 1.        , ..., 0.        , 1.        ,
        0.8       ],
       [1.        , 1.        , 0.        , ..., 1.        , 0.125     ,
        0.7       ],
       ...,
       [1.        , 0.        , 1.        , ..., 0.        , 0.        ,
        0.4       ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.75      ,
        0.6       ],
       [0.        , 0.        , 1.        , ..., 0.        , 0.5       ,
        0.5       ]])

In [57]:
x_train_processed = np.hstack((x_train_cat_encoded, x_train_float_encoded))
x_test_processed = np.hstack((x_test_cat_encoded, x_test_float_encoded))

In [58]:
feature_names = np.concatenate([obj_cols, float_cols])

In [59]:
x_train_final = pd.DataFrame(x_train_processed, columns = feature_names)

In [60]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train_processed, y_train_processed)
y_pred = lr.predict(x_test_processed)
print(accuracy_score(y_test_processed, y_pred))
print(confusion_matrix(y_test_processed, y_pred))

1.0
[[ 66   0]
 [  0 145]]


In [61]:
le.inverse_transform([0,1])

array(['No', 'Yes'], dtype=object)

In [62]:
df2 = pd.read_csv("autism_data.csv")

In [65]:
obj_cols2 = X.select_dtypes(include = 'object').columns
obj_cols2

Index(['Gender', 'Region', 'Jaundice', 'Family_mem_with_ASD',
       'Who completed the test'],
      dtype='object')

In [66]:
float_cols2 = X.select_dtypes(include = 'int64').columns
float_cols2

Index(['Q1', 'Q2', 'Q3', 'Q4', 'Q5', 'Q6', 'Q7', 'Q8', 'Q9', 'Q10',
       'Age in Months', 'Score out of 10'],
      dtype='object')

In [67]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories = [X[i].unique() for i in obj_cols2])
oe.fit(X[obj_cols2])
X_cat_encoded = oe.transform(X[obj_cols2])

In [68]:
X_cat_encoded

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [0., 1., 1., 0., 0.],
       [1., 0., 0., 1., 0.]])

In [69]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X[float_cols2])

X_float_encoded = scaler.transform(X[float_cols2])

In [70]:
X_processed = np.hstack((X_cat_encoded, X_float_encoded))

In [71]:
feature_names2 = np.concatenate([obj_cols2, float_cols2])

In [72]:
X_final = pd.DataFrame(X_processed, columns = feature_names2)

In [73]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train_processed, y_train_processed)
y_pred = lr.predict(X_processed)

In [74]:
print("ASD Possible : ", y_pred)

ASD Possible :  [1 1 0 1]
